[package]
name = "madder"
version = "0.1.0"
authors = ["myuon <ioi.joi.koi.loi@gmail.com>"]

[dependencies]
gtk = "0.3.0"
gdk = "0.7.0"
gdk-pixbuf = "0.3.0"
glib = "0.4.1"
cairo-rs = "0.3.0"
gstreamer = "0.10.1"
gstreamer-video = "0.10.1"
gstreamer-app = "0.10.1"
