version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:1.33
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: build
          working_directory: ql-server
          command: |
            sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev cmake curl
            cargo build
      - run:
          name: lint
          working_directory: ql-server
          command: |
            rustup component add clippy
            cargo clippy
      - run:
          name: test
          working_directory: ql-server
          command: |
            cargo test
