[package]
name = "cli"
version = "0.1.0"
authors = ["myuon <ioi.joi.koi.loi@gmail.com>"]

[dependencies]
madder-core = { path = "../core", version = "0.1.3" }
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
serde_yaml = "0.7.5"

