[package]
name = "api-server"
version = "0.1.0"
authors = ["myuon <ioi.joi.koi.loi@gmail.com>"]

[dependencies]
madder-core = { path = "../core", version = "0.1.3" }
ws = "0.7.6"
serde = "1.0.27"
serde_json = "1.0.9"
serde_derive = "1.0.27"

