[package]
name = "api-server"
version = "0.1.0"
authors = ["myuon <ioi.joi.koi.loi@gmail.com>"]

[dependencies]
madder-core = { path = "../core", version = "0.1.3" }
madder-util = { path = "../util", version = "0.1.2" }
ws = "0.7.6"
serde_json = "1.0.9"

